<?php

/**
 * This is the model base class for the table "virtual_aliases".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VirtualAliases".
 *
 * Columns in table "virtual_aliases" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $domain_id
 * @property string $source
 * @property string $destination
 *
 */
abstract class BaseVirtualAliases extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'virtual_aliases';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'VirtualAliases|VirtualAliases', $n);
	}

	public static function representingColumn() {
		return 'source';
	}

	public function rules() {
		return array(
			array('domain_id, source, destination', 'required'),
			array('domain_id', 'numerical', 'integerOnly'=>true),
			array('source, destination', 'length', 'max'=>100),
			array('id, domain_id, source, destination', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'domain_id' => Yii::t('app', 'Domain'),
			'source' => Yii::t('app', 'Source'),
			'destination' => Yii::t('app', 'Destination'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('domain_id', $this->domain_id);
		$criteria->compare('source', $this->source, true);
		$criteria->compare('destination', $this->destination, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}